"""Public client for the official GeoWorld product backend.

The client uses only documented HTTP endpoints and never imports private GeoWorld source.
"""

from geoworld_open.client.backend import GeoWorldBackendClient, GeoWorldClientError
from geoworld_open.client.models import (
    ArtifactInfo,
    AuthResponse,
    CapabilityCatalog,
    CapabilityDescription,
    ForgotPasswordResponse,
    JobCreateRequest,
    JobCreateResponse,
    JobResult,
    JobStatusResponse,
    LASQuicklookSettings,
    PasswordChangeResponse,
    PasswordResetResponse,
    QACitation,
    UploadedLASFile,
    UserProfile,
)
from geoworld_open.client.scientific_experiment import (
    AcquisitionRequest,
    ConversationState,
    InversionRequest,
    ModelSelection,
    RequestedOutputs,
    ScientificExperimentDraft,
)
from geoworld_open.client.marmousi_forward import (
    MarmousiAcquisitionRequest,
    MarmousiForwardExperiment,
    MarmousiForwardPreview,
    MarmousiForwardPreviewRequest,
    MarmousiForwardResult,
    MarmousiForwardSettings,
    RecordingTimeAdequacy,
    ResolvedMarmousiAcquisition,
)
from geoworld_open.client.seismic import (
    SeismicAnalysisRequest,
    SeismicAnalysisResult,
    SeismicConversationRequest,
    SeismicDatasetCatalog,
    SeismicDatasetSummary,
    SeismicExplorerResponse,
    SeismicExplorerState,
    SeismicViewData,
    SeismicViewRequest,
    SeismicWindow,
)

__all__ = [
    "AcquisitionRequest",
    "ArtifactInfo",
    "AuthResponse",
    "CapabilityCatalog",
    "CapabilityDescription",
    "ConversationState",
    "ForgotPasswordResponse",
    "GeoWorldBackendClient",
    "GeoWorldClientError",
    "InversionRequest",
    "JobCreateRequest",
    "JobCreateResponse",
    "JobResult",
    "JobStatusResponse",
    "LASQuicklookSettings",
    "MarmousiAcquisitionRequest",
    "MarmousiForwardExperiment",
    "MarmousiForwardPreview",
    "MarmousiForwardPreviewRequest",
    "MarmousiForwardResult",
    "MarmousiForwardSettings",
    "RecordingTimeAdequacy",
    "ModelSelection",
    "PasswordChangeResponse",
    "PasswordResetResponse",
    "QACitation",
    "ResolvedMarmousiAcquisition",
    "RequestedOutputs",
    "ScientificExperimentDraft",
    "SeismicAnalysisRequest",
    "SeismicAnalysisResult",
    "SeismicConversationRequest",
    "SeismicDatasetCatalog",
    "SeismicDatasetSummary",
    "SeismicExplorerResponse",
    "SeismicExplorerState",
    "SeismicViewData",
    "SeismicViewRequest",
    "SeismicWindow",
    "UploadedLASFile",
    "UserProfile",
]
