"""Offline screenshot fixture using the real Studio and an in-memory HTTP double.

The SEG-Y attachment label is simulated UI context, not a real uploaded field file.
Samples are generated by the existing public synthetic benchmark; no jobs run.
"""
from pathlib import Path
import os
import runpy

import streamlit as st

from geoworld_open.client import GeoWorldBackendClient
from geoworld_open.client.seismic import (
    SeismicConversationTurn, SeismicDatasetCatalog, SeismicExplorerResponse,
    SeismicExplorerState, SeismicViewRequest,
)
from horizon_explorer_app import API


api = API()
os.environ.setdefault("GEOWORLD_BACKEND_URL", "http://offline.example.test")
dataset = api.dataset.model_copy(update={
    "display_name": "offline_seismic_fixture.sgy", "format": "segy",
    "provenance": {"offline_ui_fixture": True, "samples": "GeoWorld synthetic benchmark"},
})


def fixture_view(request):
    request = SeismicViewRequest.model_validate(request)
    if request.view_kind == "auto":
        request = request.model_copy(update={"view_kind": "inline", "inline": 1212})
    return api.get_seismic_view(request).model_copy(update={
        "dataset": dataset, "title": "Offline seismic fixture · inline 1212",
        "selection_summary": "Inline 1212 · 64 traces · 0–1.02 s",
    })


if "assistant_capture_initialized" not in st.session_state:
    request = SeismicViewRequest(dataset_id=dataset.dataset_id, view_kind="inline", inline=1212)
    state = SeismicExplorerState(
        conversation_id="e" * 32, active_dataset_id=dataset.dataset_id, current_view=request,
        visible_history=[
            SeismicConversationTurn(user_text="Inspect my attached seismic", assistant_summary="The attached file is open. You can request an inline, crossline, trace or amplitude analysis.", status="ready"),
            SeismicConversationTurn(user_text="Show inline 1212", assistant_summary="Showing inline 1212: 64 traces at 4 ms sampling. Display clipping preserves the original samples.", status="ready"),
        ],
    )
    st.session_state.update({
        "assistant_capture_initialized": True,
        "access_token": "offline-fixture-token", "user_email": "fixture@example.test",
        "studio_active_context": "seismic", "seismic_dataset_id": dataset.dataset_id,
        "seismic_context_dataset": dataset,
        "seismic_response": SeismicExplorerResponse(state=state, view=fixture_view(request)),
    })

GeoWorldBackendClient.get_llm_health = lambda *_: {"reachable": True}
GeoWorldBackendClient.list_seismic_datasets = lambda *_: SeismicDatasetCatalog(datasets=[dataset])
GeoWorldBackendClient.get_seismic_view = lambda _self, request: fixture_view(request)


def forbidden(*_args, **_kwargs):
    raise AssertionError("The offline screenshot fixture must not submit jobs or requests.")


GeoWorldBackendClient.submit_job = forbidden
GeoWorldBackendClient.interpret_studio = forbidden
runpy.run_path(str(Path(__file__).resolve().parents[2] / "apps/studio_streamlit.py"), run_name="__main__")
